// <auto-generated />
namespace PeriodicalLiterature.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TableContract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableContract));
        
        string IMigrationMetadata.Id
        {
            get { return "201811141320171_TableContract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
